# 端口
server:
    port: 8080

# 多环境配置
spring:
    profiles:
        active: dev

## Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  typeAliasesPackage: com.ldbmcs.*
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    db-config:
      logic-delete-field: deleteStatus # 全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 2 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)